portfolio/models.py
from flask_bcrypt import generate_password_hash, check_password_hash
from flask_login import UserMixin

from portfolio import db, login_manager

@login_manager.user_loader
def load_user(user_id):
    return Restaurant.query.get(user_id)

class Restaurant(UserMixin, db.Model):
    __tablename__ = 'restaurants'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    restaurant = db.Column(db.String(30), index=True)
    password = db.Column(db.String(30))

    def __init__(self, email, restaurant, password):
        self.email = email
        self.restaurant = restaurant
        self.password = generate_password_hash(password)

    def validate_password(self, password):
        return check_password_hash(self.password, password)

    def add_user(self):
        with db.session.begin(subtransactions=True):
            db.session.add(self)
        db.session.commit()
    
    @classmethod
    def select_by_email(cls, email):
        return cls.query.filter_by(email=email).first()

portfolio/forms.py
from wtforms.form import Form
from wtforms.fields import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError

from portfolio.models import Restaurant

class LoginForm(Form):
    email = StringField('メールアドレス：', validators=[DataRequired(), Email()])
    password = PasswordField('パスワード', validators=[DataRequired()])
    submit = SubmitField('ログイン')

class SignupForm(Form):
    email = StringField('メールアドレス：', validators=[DataRequired(), Email('メールアドレスが誤っています')])
    restaurant = StringField('店名：', validators=[DataRequired()])
    password = PasswordField('パスワード：', validators=[DataRequired(), EqualTo('password_confirm', message='パスワードが一致していません。')])
    password_confirm = PasswordField('パスワード確認：', validators=[DataRequired()])
    submit = SubmitField('登録')

    def validate_email(self, field):
        if Restaurant.select_by_email(field.data):
            raise ValidationError('このメールアドレスは既に登録されています。')

portfolio/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.login_view = 'app.login'
login_manager.login_message = 'ログインをして下さい'

basedir = os.path.abspath(os.path.dirname(__name__))
db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'portfolio'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'portfolio.sqlite')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    from portfolio.views import bp
    app.register_blueprint(bp)
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    return app

portfolio/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user

from portfolio.forms import LoginForm, SignupForm
from portfolio.models import Restaurant

bp = Blueprint('app', __name__, url_prefix='')

@bp.route('/', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        restaurant = Restaurant.select_by_email(form.email.data)
        if restaurant and restaurant.validate_password(form.password.data):
            login_user(restaurant)
            return render_template('toppage.html')
    return render_template('home.html', form=form)

@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm(request.form)
    if request.method == 'POST' and form.validate():
        restaurant = Restaurant(
            email = form.email.data,
            restaurant = form.restaurant.data,
            password = form.password.data
        )
        restaurant.add_user()
        return redirect(url_for('app.login'))
    return render_template('signup.html', form=form)

portfolio/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}
    <dd>{{ field(**kwargs)| safe }}
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
</dt>
{% endmacro %}

portfolio/templates/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>portfolio</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

portfolio/templates/home.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}

{% block content %}
<h3>Welcome My Portfolio!!</h3>
{% for message in get_flashed_messages() %}
{{ message }}
{% endfor %}
<form action='/' method='POST'>
  {{form.crsf_token}}
  {{render_field(form.email)}}
  {{render_field(form.password)}}
  {{form.submit}}
</form>
<ul class="nav">
  <p>新規登録がまだの方は先に新規登録をして下さい。</p>
  <li><a href="{{url_for('app.signup')}}">新規登録</a></li>
</ul>
{% endblock %}

portfolio/templates/signup.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}

{% block content %}
<h3>Signup Page</h3>
<form action='/signup' method='POST'>
  {{form.crsf_token}}
  {{render_field(form.restaurant)}}
  {{render_field(form.email)}}
  {{render_field(form.password)}}
  {{render_field(form.password_confirm)}}
  {{form.submit}}
</form>
{% endblock %}

portfolio/templates/toppage.html
{% extends "base.html" %}

{% block content %}
<h3>Welcome  TopPage!!</h3>
{% endblock %}